### ISSUE TITLE
AjaxExceptionHandler - java.lang.IllegalStateException: CDATA tags may not nest

### ISSUE THREAD

**Issue by jherkel** [primefaces-extensions/primefaces-extensions.github.com#185]
I have played with AjaxExceptionHandler and I manually threw NullPointerException from my service layer. Unfortunately I have got this exception :
```
java.lang.IllegalStateException: CDATA tags may not nest
	at com.sun.faces.renderkit.html_basic.HtmlResponseWriter.startCDATA(HtmlResponseWriter.java:681) ~[jsf-impl-2.2.4.jar:2.2.4]
	at javax.faces.context.ResponseWriterWrapper.startCDATA(ResponseWriterWrapper.java:179) ~[jsf-api-2.2.4.jar:2.2]
	at javax.faces.context.ResponseWriterWrapper.startCDATA(ResponseWriterWrapper.java:179) ~[jsf-api-2.2.4.jar:2.2]
	at javax.faces.context.ResponseWriterWrapper.startCDATA(ResponseWriterWrapper.java:179) ~[jsf-api-2.2.4.jar:2.2]
	at javax.faces.context.ResponseWriterWrapper.startCDATA(ResponseWriterWrapper.java:179) ~[jsf-api-2.2.4.jar:2.2]
	at org.primefaces.extensions.component.ajaxerrorhandler.AjaxExceptionHandler.handlePartialResponseError(AjaxExceptionHandler.java:155) ~[primefaces-extensions-1.0.0.jar:1.0.0]
	at org.primefaces.extensions.component.ajaxerrorhandler.AjaxExceptionHandler.handle(AjaxExceptionHandler.java:82) ~[primefaces-extensions-1.0.0.jar:1.0.0]
```
I guess this article http://stackoverflow.com/a/17946483 contains the reason for this exception. Is there a possibility to integrate something like OmniPartialViewContext to primefaces AjaxExceptionHandler?

**Comment by ova2** [comment]
AjaxErrorHandler has been removed due to bugs and because PrimeFaces has a better functionality with PrimeFaces ExceptionHandler.
