### ISSUE TITLE
FluidGrid is not compatible with PrimeFaces 5.2

### ISSUE THREAD

**Issue by kito99** [primefaces-extensions/primefaces-extensions.github.com#319]
If you try to use FluidGrid (PF 3.0) and PrimeFaces 5.2, here is the exception you get:

````java
java.lang.NoSuchMethodError: org.primefaces.expression.SearchExpressionFacade.resolveComponentsForClient(Ljavax/faces/context/FacesContext;Ljavax/faces/component/UIComponent;Ljava/lang/String;)Ljava/lang/String;
        at org.primefaces.extensions.component.fluidgrid.FluidGridRenderer.encodeScript(FluidGridRenderer.java:146)
        at org.primefaces.extensions.component.fluidgrid.FluidGridRenderer.encodeEnd(FluidGridRenderer.java:57)
        at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:674)
        at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:554)
        at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:550)
        at org.apache.myfaces.renderkit.html.HtmlCompositeComponentRenderer.encodeChildren(HtmlCompositeComponentRenderer.java:66)
        at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:643)
        at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:541)
        at org.apache.myfaces.shared.renderkit.RendererUtils.renderChildren(RendererUtils.java:688)
        at org.apache.myfaces.shared.renderkit.html.HtmlGroupRendererBase.encodeEnd(HtmlGroupRendererBase.java:109)
        at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:674)
        at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:554)
        at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:550)
        at org.apache.myfaces.shared.renderkit.RendererUtils.renderChildren(RendererUtils.java:688)
        at org.apache.myfaces.shared.renderkit.html.HtmlGroupRendererBase.encodeEnd(HtmlGroupRendererBase.java:109)
        at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:674)
        at org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:88)
        at org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:71)
        at org.primefaces.extensions.component.layout.LayoutPaneRenderer.encodeBegin(LayoutPaneRenderer.java:152)
        at javax.faces.component.UIComponentBase.encodeBegin(UIComponentBase.java:596)
        at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:526)
        at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:550)
        at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:550)
        at javax.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:550)
        at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.renderView(FaceletViewDeclarationLanguage.java:1891)
        at org.apache.myfaces.application.ViewHandlerImpl.renderView(ViewHandlerImpl.java:313)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:58)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:58)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:58)
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:58)
        at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:116)
        at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:267)
        at org.apache.myfaces.extensions.cdi.jsf2.impl.listener.phase.CodiLifecycleWrapper.render(CodiLifecycleWrapper.java:126)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:200)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:130)
        at ienv.ienvision.web.security.IEnvisionSecurityFilter.handlePageRequest(IEnvisionSecurityFilter.java:69)
        at ienv.security.ETSSecurityFilter.doFilter(ETSSecurityFilter.java:146)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
        at org.primefaces.webapp.filter.FileUploadFilter.doFilter(FileUploadFilter.java:78)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:85)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:61)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:25)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:113)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:56)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:25)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:45)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:61)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:70)
        at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:25)
        at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:25)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:25)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:240)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:227)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:73)
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:146)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:177)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:727)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

'''''

**Comment by tandraschko** [comment]
Hey Kito,

trunk is already compatible with 5.2. We will ship a release soon.

**Comment by ova2** [comment]
Kito, no worries I will release 3.1.0 this week. 3.1.0 is fully compaible with PF 5.2. Thanks.

**Comment by kito99** [comment]
Thanks for the update, Oleg.
