### ISSUE TITLE
Sheet: JSONException when pasting more rows than available in the current sheet

### ISSUE THREAD

**Issue by blutorange** [primefaces-extensions/primefaces-extensions.github.com#586]
## Version

Tested on PrimeFaces Extensions Showcase, PrimeFaces: 6.2, PrimeFaces Extensions: 6.2.5, JSF: mojarra 2.3.2, Server: jetty/9.4.2.v20170220, Build time: 2018-06-19 16:16

## Steps to reproduce

1. Go to https://www.primefaces.org/showcase-ext/sections/sheet/ajaxEvents.jsf
1. Copy the text below to the clipboard.
1. Select the last column "Editable" by clicking on it (or select the first cell of that columm).
1. Paste the contents of the clipboard by pressing ctrl+v.
1. An error page appears, with the stack trace below.

This seems to happen whenever you paste more rows than are available in the current sheet.

## The stack trace

```text
Oops, an unexpected error occured
Message: JSONArray[4] not a string. 
Timestamp: 2018-07-05 09:18:22 
StackTrace: org.primefaces.json.JSONException: JSONArray[4] not a string.
at org.primefaces.json.JSONArray.getString(JSONArray.java:418)
at org.primefaces.extensions.component.sheet.SheetRenderer.decodeSubmittedValues(SheetRenderer.java:914)
at org.primefaces.extensions.component.sheet.SheetRenderer.decode(SheetRenderer.java:768)
at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:858)
at javax.faces.component.UIInput.decode(UIInput.java:822)
at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1263)
at javax.faces.component.UIInput.processDecodes(UIInput.java:716)
at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:629)
at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:183)
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1736)
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
at javax.faces.component.UIForm.visitTree(UIForm.java:386)
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
at javax.faces.component.UIComponent.visitTree(UIComponent.java:1747)
at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:423)
at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:284)
at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:57)
at javax.faces.context.PartialViewContextWrapper.processPartial(PartialViewContextWrapper.java:252)
at org.omnifaces.context.OmniPartialViewContext.processPartial(OmniPartialViewContext.java:143)
at javax.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:1030)
at com.sun.faces.lifecycle.ApplyRequestValuesPhase.execute(ApplyRequestValuesPhase.java:79)
at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:100)
at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:201)
at javax.faces.webapp.FacesServlet.service(FacesServlet.java:670)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
at org.omnifaces.filter.CacheControlFilter.doFilter(CacheControlFilter.java:238)
at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
at org.omnifaces.filter.GzipResponseFilter.doFilter(GzipResponseFilter.java:180)
at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:206)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
at org.omnifaces.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:123)
at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1613)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:541)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1592)
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1561)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:118)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
at org.eclipse.jetty.server.Server.handle(Server.java:564)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
at java.lang.Thread.run(Thread.java:745)
```

## The text to copy to the clipboard
```text
365
258
9
525
771
95
178
232
235
148
26
729
290
673
376
215
360
153
770
782
871
329
698
525
793
595
746
114
595
308
250
170
619
489
40
314
740
864
721
620
988
666
620
70
504
370
422
152
317
902
848
441
95
842
302
183
147
334
566
130
725
230
241
553
845
484
425
952
561
20
245
406
473
157
123
30
159
754
658
179
226
381
65
725
44
936
256
11
9
949
857
972
548
98
367
504
421
318
768
972
93
574
792
790
950
747
200
473
630
513
394
644
725
363
300
68
794
789
335
319
656
273
96
226
172
257
981
956
170
881
74
343
482
154
310
475
911
850
408
854
497
106
492
412
122
132
687
562
81
517
417
572
433
843
218
365
258
9
525
771
95
178
232
235
148
26
729
290
673
376
215
360
153
770
782
871
329
698
525
793
595
746
114
595
308
250
170
619
489
40
314
740
864
721
620
988
666
620
70
504
370
422
152
317
902
848
441
95
842
302
183
147
334
566
130
725
230
241
553
845
484
425
952
561
20
245
406
473
157
123
30
159
754
658
179
226
381
65
725
44
936
256
11
9
949
857
972
548
98
367
504
421
318
768
972
93
574
792
790
950
747
200
473
630
513
394
644
725
363
300
68
794
789
335
319
656
273
96
226
172
257
981
956
170
881
74
343
482
154
310
475
911
850
408
854
497
106
492
412
122
132
687
562
81
517
417
572
433
843
218
```

**Comment by melloware** [comment]
Thanks for reporting.  I will fix it.

**Comment by blutorange** [comment]
Thanks for the quick reply. I see that 6.2.7 was just released. I tried it and I can confirm that it works now, additional columns are added. I think this is the right behavior.

However, when a listener is added for the `change` event of the bean, `Sheet#getUpdates` does not return the updates for the newly added cells. Is this the intended behavior? Should I create a new issue for this?
