### ISSUE TITLE
DataExporter does not implement UIComponent but is listed as a component in faces-config.xml

### ISSUE THREAD

**Issue by stiemannkj1** [primefaces-extensions/primefaces-extensions.github.com#603]
Steps to reproduce:

1. Create the following **`Listener.java`** class file:

```
public class Listener implements SystemEventListener {

	@Override
	public void processEvent(SystemEvent event) throws AbortProcessingException {

		System.err.println("-------------------------------------------------------------------");

		Application application = (Application) event.getSource();
		Iterator<String> iterator = application.getComponentTypes();

		while (iterator.hasNext()) {

			String componentType = iterator.next();

			try {
				UIComponent uiComponent = application.createComponent(componentType);
			}
			catch (Throwable t) {

				t.printStackTrace(System.err);
				System.err.println("-------------------------------------------------------------------");
			}
		}
	}

	@Override
	public boolean isListenerForSource(Object source) {
		return source instanceof Application;
	}
}
```

2. Register `Listener` as a listener for the `PostConstructApplicationEvent` in the application's **`WEB-INF/faces-config.xml`**:

```
	<application>
		<system-event-listener>
			<system-event-class>javax.faces.event.PostConstructApplicationEvent
</system-event-class>
			<system-event-listener-class>package.for.my.Listener</system-event-listener-class>
		</system-event-listener>
	</application>
```

3. Deploy the application (with PrimeFaces 6.2 and PrimeFaces Extensions 6.2.7).

If the bug still exists, the following message will appear in the logs:

```
-------------------------------------------------------------------
09-Aug-2018 12:19:41.696 SEVERE [localhost-startStop-2] com.sun.faces.application.ApplicationImpl.createComponentApplyAnnotations JSF1068: Cannot instantiate component with component-type org.primefaces.extensions.component.DataExporter
javax.faces.FacesException: java.lang.ClassCastException: org.primefaces.extensions.component.exporter.DataExporter cannot be cast to javax.faces.component.UIComponent
        at com.sun.faces.application.ApplicationImpl.createComponentApplyAnnotations(ApplicationImpl.java:1903)
        at com.sun.faces.application.ApplicationImpl.createComponent(ApplicationImpl.java:926)
        at com.liferay.faces.test.jsf.Listener.processEvent(Listener.java:44)
        at javax.faces.event.SystemEvent.processListener(SystemEvent.java:108)
        at com.sun.faces.application.ApplicationImpl.processListeners(ApplicationImpl.java:2169)
        at com.sun.faces.application.ApplicationImpl.invokeListenersFor(ApplicationImpl.java:2142)
        at com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:301)
        at com.sun.faces.config.ConfigManager.publishPostConfigEvent(ConfigManager.java:704)
        at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:270)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4810)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:939)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1812)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: org.primefaces.extensions.component.exporter.DataExporter cannot be cast to javax.faces.component.UIComponent
        at com.sun.faces.application.ApplicationImpl.createComponentApplyAnnotations(ApplicationImpl.java:1896)
        ... 21 more
-------------------------------------------------------------------
```

If the bug is fixed, then the above message won't appear in the logs.

**Comment by melloware** [comment]
Thanks for the fix!
