### ISSUE TITLE
DynaForm throws NPE

### ISSUE THREAD

**Issue by tandraschko** [primefaces-extensions/primefaces-extensions.github.com#644]
This commit breaks the application of my customer:
https://github.com/primefaces-extensions/core/commit/9c8a1f189c4fb4d60416471fa07ff7fe7328c6ac#diff-fe3223c5845645bada5eef70c9f1bceb

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.faces.component._ComponentAttributesMap.getComponentProperty(_ComponentAttributesMap.java:685)
	at javax.faces.component._ComponentAttributesMap.get(_ComponentAttributesMap.java:319)
	at org.primefaces.extensions.component.base.AbstractDynamicData.saveDescendantState(AbstractDynamicData.java:576)
	at org.primefaces.extensions.component.base.AbstractDynamicData.saveDescendantState(AbstractDynamicData.java:580)
	at org.primefaces.extensions.component.base.AbstractDynamicData.saveDescendantState(AbstractDynamicData.java:541)
	at org.primefaces.extensions.component.base.AbstractDynamicData.setData(AbstractDynamicData.java:164)
	at org.primefaces.extensions.component.base.AbstractDynamicData.visitTree(AbstractDynamicData.java:434)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1047)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
	at javax.faces.component.UINamingContainer.visitTree(UINamingContainer.java:177)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1047)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1047)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
	at javax.faces.component.UIForm.visitTree(UIForm.java:345)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1047)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1047)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1047)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1192)
	at org.omnifaces.util.Components$ForEach.invoke(Components.java:566)
	at org.omnifaces.util.Components$ForEach.invoke(Components.java:526)
	at org.omnifaces.viewhandler.OmniViewHandler.checkNestedForms(OmniViewHandler.java:191)
	at org.omnifaces.viewhandler.OmniViewHandler.validateComponentTreeStructure(OmniViewHandler.java:187)
	at org.omnifaces.viewhandler.OmniViewHandler.renderView(OmniViewHandler.java:112)
	at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:116)
	at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:267)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:200)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.openejb.server.httpd.EEFilter.doFilter(EEFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:44)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.tomee.catalina.OpenEJBSecurityListener$RequestCapturer.invoke(OpenEJBSecurityListener.java:97)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.myfaces.view.facelets.el.ContextAwarePropertyNotFoundException: javax.el.PropertyNotFoundException: Property 'name' not found on type java.lang.String
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:100)
	at org.apache.myfaces.view.facelets.el.LocationValueExpression.getValue(LocationValueExpression.java:127)
	at javax.faces.component._DeltaStateHelper.eval(_DeltaStateHelper.java:377)
	at javax.faces.component.html.HtmlInputText.isDisabled(HtmlInputText.java:421)
	... 62 more
Caused by: javax.el.PropertyNotFoundException: Property 'name' not found on type java.lang.String
	at javax.el.BeanELResolver$BeanProperties.get(BeanELResolver.java:259)
	at javax.el.BeanELResolver$BeanProperties.access$300(BeanELResolver.java:212)
	at javax.el.BeanELResolver.property(BeanELResolver.java:346)
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:92)
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:62)
	at org.apache.myfaces.el.unified.resolver.FacesCompositeELResolver.getValue(FacesCompositeELResolver.java:179)
	at org.apache.el.parser.AstValue.getValue(AstValue.java:169)
	at org.apache.el.parser.AstMethodParameters.getParameters(AstMethodParameters.java:33)
	at org.apache.el.parser.AstValue.getValue(AstValue.java:158)
	at org.apache.el.parser.AstOr.getValue(AstOr.java:42)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:184)
	at org.apache.webbeans.el22.WrappedValueExpression.getValue(WrappedValueExpression.java:70)
	at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getValue(ContextAwareTagValueExpression.java:96)

```

**Comment by tandraschko** [comment]
i'm not sure why but the problem is that the dynaForm var is acessed in a rendered flag and null in this case.
As the disabled state was not saved/restored before, it never occured

**Comment by melloware** [comment]
Ahhh crap.  We need to remove that I thought I had removed it from everywhere.
