### ISSUE TITLE
Showcase (?) InputPhone submit causes Unrecognized Content Type

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions.github.com#688]
Can be tested wit the showcase. Must be something that has changed recently.

```
java.lang.IllegalArgumentException: Unrecognized Content Type.
at com.sun.faces.renderkit.RenderKitImpl.createResponseWriter(RenderKitImpl.java:259)
at com.sun.faces.application.view.FaceletViewHandlingStrategy.createResponseWriter(FaceletViewHandlingStrategy.java:1125)
at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:415)
at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:170)
at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132)
```

needs further testing.. might be something in the showcase

**Comment by jepsar** [comment]
This was only happening with Payara 5.191.
