### ISSUE TITLE
Component: MasterDetail / ExtLangUtils

### ISSUE THREAD

**Issue by fheldt** [primefaces-extensions/primefaces-extensions.github.com#811]
**Bug description**
After switching from V8.0.2 to V8.0.3 I get a NPE in the MasterDetail component.

SEVERE [javax.enterprise.resource.webcontainer.jsf.application] (default task-3399) Error Rendering View[/xxx/yyy.xhtml]: java.lang.NullPointerException
        at deployment.gm-portal-ear.ear.gm-portal-web.war//org.primefaces.extensions.util.ExtLangUtils.contains(ExtLangUtils.java:31)
        at deployment.gm-portal-ear.ear.gm-portal-web.war//org.primefaces.extensions.component.masterdetail.MasterDetailRenderer.encodeEnd(MasterDetailRenderer.java:78)
        at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:595)
        at javax.faces.api@3.0.0.SP04//javax.faces.component.UIComponent.encodeAll(UIComponent.java:1654)

Maybe ExtLangUtils.contains should be guided against null parameters.
V8.0.2 works perfectly well here.

**Environment:**
 - PF Version: _8.0_
 - JSF + version: Mojarra 2.3.9.SP11

**Comment by melloware** [comment]
Thanks its fixed for 8.0.4!

Commit: https://github.com/primefaces-extensions/core/commit/fb90483c8409d21f22d7462c14939d19c7b3b1cf
